language: php

php:
  - 5.6
  - 7.0

branches:
  only:
    - master
    
install:
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar -O "$HOME/ocular.phar"
  
script:
  - vendor/bin/phpunit --coverage-clover cache/logs/clover.xml

after_success:
  - test ${TRAVIS_PHP_VERSION:0:3} != "7.0" || php "$HOME/ocular.phar" code-coverage:upload --format=php-clover cache/logs/clover.xml
